spring:
  application:
    name: api
  profiles:
    active: develop
  jpa:
    open-in-view: false
server:
  port: 13713
  servlet:
    context-path: /ajp-api
    encoding:
      charset: utf-8
      enabled: true
      force: true
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: / #swagger redirect /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    display-operation-id: true
    filter: true
security:
  jwt:
    secret-key: Y29tLnRpc3RvcnkuYWxqamFiYWVnaWNvbS50aXN0b3J5LmFsamphYmFlZ2ljb20udGlzdG9yeS5hbGpqYWJhZWdp #base64 encoding
    issuer: aljjabaegi.tistory.com

--- #develop

spring:
  config:
    activate:
      on-profile: develop
  datasource:
    #    url: "jdbc:mariadb://211.41.186.111:3306/API_TEST_DB" #mariadb
    #    driver-class-name: "org.mariadb.jdbc.Driver" #mariadb
    url: "jdbc:postgresql://localhost:15432/test_db"
    driver-class-name: "org.postgresql.Driver"
    username: aljjabaegi
    password: aljjabaegi123!@#
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create