spring:
  application:
    name: api
server:
  port: 13713
  servlet:
    context-path: /ajp-api
    encoding:
      charset: utf-8
      enabled: true
      force: true
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: / #swagger redirect /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    display-operation-id: true
    filter: true