spring:
  application:
    name: api
server:
  port: 13713
  servlet:
    context-path: /ajp-api
    encoding:
      charset: utf-8
      enabled: true
      force: true
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: / #swagger redirect /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    display-operation-id: true
    filter: true

--- #develop

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mariadb://211.41.186.111:3306/API_TEST_DB"
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: api_test
    password: api_test
  jpa:
    show-sql: true